name: example
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  records: ^0.0.0
dependency_overrides:
  records:
    path: ../records
    
dev_dependencies:
  build_runner:
  records_generator:
    path: ../records_generator
